# Address to bind to
# 0.0.0.0 to listen to all
# 127.0.0.1 to localhost for testing
# 192.168.0.1 typically for a specific interface
BIND_ADDRESS: '0.0.0.0'

# Port the server will be listening. Defaults 54154 (SALSA)
LISTENING_PORT: 54154

# Tuples of (port, protocol) that will be opened/closed.
# Port range: 1-65535
# protocol: 'udp', 'tcp'
PORTS:
  - port: 80
    protocol: tcp
  - port: 443
    protocol: tcp

# Certificate of the server
CERT_FILE: "../certs/server.crt"

# Private key of the server certificate
KEY_FILE: "../certs/server.key"

# Certification authority (CA) root certificate.
# Only clients that have connected to the server using a certificate
# issued by this authority will go through.
CA_CERT_FILE: "../certs/ca.crt"

# Enable debug messages
DEBUG: true