package org.merlos.openme.ui.screens

import android.Manifest
import android.content.pm.PackageManager
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.google.zxing.integration.android.IntentIntegrator
import org.merlos.openme.ui.ProfileViewModel

/**
 * Import profile screen — two tabs: YAML paste and QR scan.
 *
 * **YAML tab**: The user pastes the output of `openme add <profile-name>`
 * (or the full `~/.openme/config.yaml` file). Whitespace and case are preserved.
 *
 * **QR tab**: Launches the device camera via ZXing to scan an openme QR code
 * generated by `openme qr <profile-name>`. The QR payload is a compact JSON
 * object — see [ClientConfigParser.parseQRPayload].
 *
 * @param startOnQrTab When `true`, the QR tab is pre-selected on entry.
 * @param onDone Callback invoked after a successful import; typically navigates back.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ImportProfileScreen(
    viewModel: ProfileViewModel,
    startOnQrTab: Boolean = false,
    onBack: () -> Unit,
    onDone: () -> Unit,
) {
    val importError by viewModel.importError.collectAsStateWithLifecycle()
    var selectedTab by remember { mutableIntStateOf(if (startOnQrTab) 1 else 0) }

    // Clear error on tab switch
    LaunchedEffect(selectedTab) { viewModel.clearImportError() }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Import Profile") },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.primaryContainer,
                    titleContentColor = MaterialTheme.colorScheme.onPrimaryContainer,
                ),
            )
        },
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .padding(paddingValues)
                .fillMaxSize(),
        ) {
            TabRow(selectedTabIndex = selectedTab) {
                Tab(
                    selected = selectedTab == 0,
                    onClick = { selectedTab = 0 },
                    text = { Text("YAML") },
                    icon = { Icon(Icons.Filled.Description, null) },
                )
                Tab(
                    selected = selectedTab == 1,
                    onClick = { selectedTab = 1 },
                    text = { Text("QR Code") },
                    icon = { Icon(Icons.Filled.QrCodeScanner, null) },
                )
            }

            // Error banner
            importError?.let { msg ->
                Surface(
                    color = MaterialTheme.colorScheme.errorContainer,
                    modifier = Modifier.fillMaxWidth(),
                ) {
                    Row(
                        modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Icon(
                            Icons.Filled.ErrorOutline,
                            contentDescription = null,
                            tint = MaterialTheme.colorScheme.onErrorContainer,
                        )
                        Spacer(Modifier.width(8.dp))
                        Text(
                            msg,
                            color = MaterialTheme.colorScheme.onErrorContainer,
                            style = MaterialTheme.typography.bodySmall,
                        )
                    }
                }
            }

            when (selectedTab) {
                0 -> YamlImportTab(viewModel = viewModel, onDone = onDone)
                1 -> QrImportTab(viewModel = viewModel, onDone = onDone)
            }
        }
    }
}

// ─── YAML tab ─────────────────────────────────────────────────────────────────

@Composable
private fun YamlImportTab(viewModel: ProfileViewModel, onDone: () -> Unit) {
    var yaml by remember { mutableStateOf("") }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp),
    ) {
        Text(
            text = "Paste the output of openme add <profile-name> below.",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )

        OutlinedTextField(
            value = yaml,
            onValueChange = { yaml = it },
            modifier = Modifier
                .fillMaxWidth()
                .heightIn(min = 180.dp),
            label = { Text("config.yaml content") },
            placeholder = {
                Text(
                    "profiles:\n    my-server:\n        server_host: \"...\"\n        ...",
                    fontFamily = FontFamily.Monospace,
                )
            },
            textStyle = LocalTextStyle.current.copy(fontFamily = FontFamily.Monospace),
        )

        Button(
            onClick = { viewModel.importYaml(yaml, onDone) },
            modifier = Modifier.fillMaxWidth(),
            enabled = yaml.isNotBlank(),
        ) {
            Icon(Icons.Filled.FileDownload, null)
            Spacer(Modifier.width(8.dp))
            Text("Import")
        }
    }
}

// ─── QR tab ───────────────────────────────────────────────────────────────────

@Composable
private fun QrImportTab(viewModel: ProfileViewModel, onDone: () -> Unit) {
    val context = LocalContext.current
    var cameraGranted by remember {
        mutableStateOf(
            ContextCompat.checkSelfPermission(context, Manifest.permission.CAMERA)
                == PackageManager.PERMISSION_GRANTED
        )
    }

    val permissionLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.RequestPermission()
    ) { granted -> cameraGranted = granted }

    // ZXing scan result launcher
    val scanLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.StartActivityForResult()
    ) { result ->
        val scanResult = IntentIntegrator.parseActivityResult(result.resultCode, result.data)
        scanResult?.contents?.let { json ->
            viewModel.importQr(json, onDone)
        }
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(32.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Icon(
            Icons.Filled.QrCodeScanner,
            contentDescription = null,
            modifier = Modifier.size(80.dp),
            tint = MaterialTheme.colorScheme.primary.copy(alpha = 0.6f),
        )
        Spacer(Modifier.height(16.dp))
        Text(
            "Scan the QR code generated by:",
            style = MaterialTheme.typography.bodyMedium,
        )
        Spacer(Modifier.height(4.dp))
        Surface(
            color = MaterialTheme.colorScheme.surfaceVariant,
            shape = MaterialTheme.shapes.small,
        ) {
            Text(
                "openme qr <profile-name>",
                style = MaterialTheme.typography.bodyMedium,
                fontFamily = FontFamily.Monospace,
                modifier = Modifier.padding(horizontal = 12.dp, vertical = 6.dp),
            )
        }
        Spacer(Modifier.height(32.dp))

        Button(
            onClick = {
                if (!cameraGranted) {
                    permissionLauncher.launch(Manifest.permission.CAMERA)
                } else {
                    val integrator = IntentIntegrator.forFragment(null)
                    // Build scan intent directly
                    val intent = IntentIntegrator(
                        context as? androidx.activity.ComponentActivity
                    ).apply {
                        setDesiredBarcodeFormats(IntentIntegrator.QR_CODE)
                        setPrompt("Align the openme QR code")
                        setBeepEnabled(false)
                        setOrientationLocked(false)
                    }.createScanIntent()
                    scanLauncher.launch(intent)
                }
            },
            modifier = Modifier.fillMaxWidth(),
        ) {
            Icon(Icons.Filled.CameraAlt, null)
            Spacer(Modifier.width(8.dp))
            Text("Open Camera")
        }
    }
}
